service: typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  versionFunctions: false

functions:
  api:
    handler: .build/src/server.handler
    events:
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-offline

package:
  patterns:
    - '!package-lock.json'
    - '!tsconfig.json'
    - '!nodemon.json'
    - '!yarn.lock'
    - '!README.md'
    - '!src/**'